/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jframe;

import java.awt.*;
import java.util.ArrayList;
import model.MyCircle;
import model.MyPoint;
import model.MyRectangle;
import model.MyTriangle;

/**
 *
 * @author elorza.karmele
 */
public class JFrameKoordenatuak extends javax.swing.JFrame {

    /**
     * Creates new form JFrameKoordenatuak
     */
    public JFrameKoordenatuak() {
        this.setResizable(false);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jPanel = new javax.swing.JPanel();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setTitle("KOORDENATUAK");

            jPanel.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jPanelMouseClicked(evt);
                  }
                  public void mousePressed(java.awt.event.MouseEvent evt) {
                        jPanelMousePressed(evt);
                  }
                  public void mouseReleased(java.awt.event.MouseEvent evt) {
                        jPanelMouseReleased(evt);
                  }
            });
            jPanel.addKeyListener(new java.awt.event.KeyAdapter() {
                  public void keyPressed(java.awt.event.KeyEvent evt) {
                        jPanelKeyPressed(evt);
                  }
            });

            javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
            jPanel.setLayout(jPanelLayout);
            jPanelLayout.setHorizontalGroup(
                  jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGap(0, 500, Short.MAX_VALUE)
            );
            jPanelLayout.setVerticalGroup(
                  jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGap(0, 433, Short.MAX_VALUE)
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            pack();
      }// </editor-fold>//GEN-END:initComponents

      /**
       * 
       * @param evt -ek erabiltzailearen clickaren kudeaketa egiten du.
       * Funtzio hau erabili da hainbat elementu marrazteko: zuzenak, puntuak, laukizuzenak, triangeluak eta zirkuluak.
       * //Aukera aldagaia eskus aldatu behar da aukera ezberdinak exekutatzeko!!
       */
      private void jPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMousePressed
          // TODO add your handling code here:  

          float hue = (float) (Math.random());
          int rgb = Color.HSBtoRGB(hue, 1F, 1F), height, width;
          Color color = new Color(rgb);
          koordenadak = new MyPoint(evt.getX() + 4, evt.getY() + 25);
          koord.add(koordenadak);

          Graphics g = getGraphics();
          g.setColor(color);
          g.fillOval(koordenadak.getX(), koordenadak.getY(), 4, 4);
          g.drawString("(" + koordenadak.getX() + "," + koordenadak.getY() + ")", koordenadak.getX(), koordenadak.getY());

          if (aukera == 1) { //aukera = zuzen bat marraztu
              if (koord.size() % 2 == 0) {
                  g.setColor(Color.BLACK);
                  g.drawLine(koord.get(kontLine * 2).getX(), koord.get(kontLine * 2).getY(), koord.get(kontLine * 2 + 1).getX(), koord.get(kontLine * 2 + 1).getY());
                  kontLine++;
              }
          }

          if (aukera == 2) { //aukera = triangulu bat marraztu  
              if (koord.size() % 3 == 0) {
                  triangulua = new MyTriangle(koord.get(kontTriangle * 3).getX(), koord.get(kontTriangle * 3).getY(), koord.get(kontTriangle * 3 + 1).getX(), koord.get(kontTriangle * 3 + 1).getY(), koord.get(kontTriangle * 3 + 2).getX(), koord.get(kontTriangle * 3 + 2).getY());
                  g.setColor(Color.BLACK);
                  g.drawPolygon(new int[]{triangulua.getV1().getX(), triangulua.getV2().getX(), triangulua.getV3().getX()}, new int[]{triangulua.getV1().getY(), triangulua.getV2().getY(), triangulua.getV3().getY()}, 3);
                  kontTriangle++;
              }
          }

          if (aukera == 3) { //aukera = zirkulu bat marraztu  
              if (koord.size() % 1 == 0) {
                  zirkulua = new MyCircle(koord.get(kontCircle).getX(), koord.get(kontCircle).getY(), 21);
                  g.setColor(Color.BLACK);
                  g.drawOval(zirkulua.getCenterX(), zirkulua.getCenterY(), (int) zirkulua.getRadius(), (int) zirkulua.getRadius());
                  kontCircle++;
              }
          }

          if (aukera == 4) { //aukera = laukizuzen bat marraztu  
              if (koord.size() % 2 == 0) {
                  g.setColor(Color.BLACK);
                  laukizuzena = new MyRectangle(koord.get(kontRectangle * 2), koord.get(kontRectangle * 2 + 1));
                  if ((laukizuzena.getBottonRightt().getX() < laukizuzena.getTopLeft().getX()) && (laukizuzena.getBottonRightt().getY() < laukizuzena.getTopLeft().getY())) {
                      height = laukizuzena.getTopLeft().getY() - laukizuzena.getBottonRightt().getY();
                      width = laukizuzena.getTopLeft().getX() - laukizuzena.getBottonRightt().getX();
                      g.drawRect(laukizuzena.getBottonRightt().getX(), laukizuzena.getBottonRightt().getY(), width, height);
                  }
                  if ((laukizuzena.getBottonRightt().getX() >= laukizuzena.getTopLeft().getX()) && (laukizuzena.getBottonRightt().getY() >= laukizuzena.getTopLeft().getY())) {
                      height = laukizuzena.getBottonRightt().getY() - laukizuzena.getTopLeft().getY();
                      width = laukizuzena.getBottonRightt().getX() - laukizuzena.getTopLeft().getX();
                      g.drawRect(laukizuzena.getTopLeft().getX(), laukizuzena.getTopLeft().getY(), width, height);
                  }
                  if ((laukizuzena.getBottonRightt().getX() < laukizuzena.getTopLeft().getX()) && (laukizuzena.getBottonRightt().getY() >= laukizuzena.getTopLeft().getY())) {
                      height = laukizuzena.getBottonRightt().getY() - laukizuzena.getTopLeft().getY();
                      width = laukizuzena.getTopLeft().getX() - laukizuzena.getBottonRightt().getX();
                      g.drawRect(laukizuzena.getTopLeft().getX() - width, laukizuzena.getTopLeft().getY(), width, height);
                  }
                  if ((laukizuzena.getBottonRightt().getX() >= laukizuzena.getTopLeft().getX()) && (laukizuzena.getBottonRightt().getY() < laukizuzena.getTopLeft().getY())) {
                      height = laukizuzena.getTopLeft().getY() - laukizuzena.getBottonRightt().getY();
                      width = laukizuzena.getBottonRightt().getX() - laukizuzena.getTopLeft().getX();
                      g.drawRect(laukizuzena.getBottonRightt().getX() - width, laukizuzena.getBottonRightt().getY(), width, height);
                  }
                  kontRectangle++;
              }
          }


      }//GEN-LAST:event_jPanelMousePressed

      private void jPanelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanelKeyPressed
          // TODO add your handling code here:
      }//GEN-LAST:event_jPanelKeyPressed

      private void jPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMouseClicked
          // TODO add your handling code here:


      }//GEN-LAST:event_jPanelMouseClicked

      private void jPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMouseReleased
          // TODO add your handling code here:
      }//GEN-LAST:event_jPanelMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameKoordenatuak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameKoordenatuak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameKoordenatuak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameKoordenatuak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameKoordenatuak().setVisible(true);
                   //aukeren kudeaketa bururtzeko, hasieran ireki jframe berria eta gero dispose egin???
            }
        });
    }

    public void paint(Graphics g) {
        g.setColor(Color.RED);
        g.fillRect(this.getWidth() / 2, 0, 2, this.getWidth());
        g.fillRect(0, this.getWidth() / 2, this.getWidth(), 2);
    }

    MyPoint koordenadak;
    MyTriangle triangulua;
    MyCircle zirkulua;
    MyRectangle laukizuzena;
    ArrayList<MyPoint> koord = new ArrayList<MyPoint>();
    int kontTriangle = 0, kontLine = 0, kontCircle = 0, kontRectangle = 0;
    int aukera = 4; //Eskus aldatu behar da aukera ezberdinak exekutatzeko.

      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JPanel jPanel;
      // End of variables declaration//GEN-END:variables
}
