/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg1;
/**
 *
 * @author elorza.karmele
 */
public class View extends javax.swing.JFrame {

      /**
       * Creates new form View
       */
      public View() {
            initComponents();
      }
      
      public static View viewaSortuBistaratu() {
        View v = new View();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                v.setVisible(true);
            }
        });
        return v;
      }
      /**
       * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jLabelTitulua = new javax.swing.JLabel();
            jLabelEus = new javax.swing.JLabel();
            jLabelEsp = new javax.swing.JLabel();
            jButtonImprimatu = new javax.swing.JButton();
            jTextFieldEus = new javax.swing.JTextField();
            jButtonTxertatu = new javax.swing.JButton();
            jTextFieldEsp = new javax.swing.JTextField();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setBackground(new java.awt.Color(109, 179, 238));

            jLabelTitulua.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
            jLabelTitulua.setText("HITZ BERRIA");

            jLabelEus.setText("Euskaraz: ");

            jLabelEsp.setText("Gazteleraz:");

            jButtonImprimatu.setText("Imprimatu");
            jButtonImprimatu.setActionCommand("IMPRIMATU");
            jButtonImprimatu.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButtonImprimatuActionPerformed(evt);
                  }
            });

            jTextFieldEus.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jTextFieldEusActionPerformed(evt);
                  }
            });

            jButtonTxertatu.setText("Txertatu");
            jButtonTxertatu.setActionCommand("TXERTATU");
            jButtonTxertatu.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButtonTxertatuActionPerformed(evt);
                  }
            });

            jTextFieldEsp.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jTextFieldEspActionPerformed(evt);
                  }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                    .addGap(35, 35, 35)
                                    .addComponent(jLabelTitulua))
                              .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                          .addComponent(jLabelEsp)
                                          .addComponent(jLabelEus))
                                    .addGap(32, 32, 32)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                          .addComponent(jTextFieldEus, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                          .addComponent(jTextFieldEsp))))
                        .addContainerGap(37, Short.MAX_VALUE))
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonImprimatu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonTxertatu)
                        .addGap(78, 78, 78))
            );
            layout.setVerticalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabelTitulua)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(jLabelEus)
                              .addComponent(jTextFieldEus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jLabelEsp)
                              .addComponent(jTextFieldEsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jButtonImprimatu)
                              .addComponent(jButtonTxertatu))
                        .addGap(50, 50, 50))
            );

            pack();
      }// </editor-fold>//GEN-END:initComponents

      private void jTextFieldEusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEusActionPerformed
            // TODO add your handling code here:
      }//GEN-LAST:event_jTextFieldEusActionPerformed

      private void jButtonImprimatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimatuActionPerformed
            // TODO add your handling code here:
      }//GEN-LAST:event_jButtonImprimatuActionPerformed

      private void jButtonTxertatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTxertatuActionPerformed
            // TODO add your handling code here:
      }//GEN-LAST:event_jButtonTxertatuActionPerformed

      private void jTextFieldEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEspActionPerformed
            // TODO add your handling code here:
      }//GEN-LAST:event_jTextFieldEspActionPerformed

      /**
       * @param args the command line arguments
       */
      /*public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             
            try {
                  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                              javax.swing.UIManager.setLookAndFeel(info.getClassName());
                              break;
                        }
                  }
            } catch (ClassNotFoundException ex) {
                  java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                  java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                  java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                  java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form 
            java.awt.EventQueue.invokeLater(new Runnable() {
                  public void run() {
                        new View().setVisible(true);
                  }
            });
      }*/

      // Variables declaration - do not modify//GEN-BEGIN:variables
      javax.swing.JButton jButtonImprimatu;
      javax.swing.JButton jButtonTxertatu;
      private javax.swing.JLabel jLabelEsp;
      private javax.swing.JLabel jLabelEus;
      private javax.swing.JLabel jLabelTitulua;
      javax.swing.JTextField jTextFieldEsp;
      javax.swing.JTextField jTextFieldEus;
      // End of variables declaration//GEN-END:variables
}
