/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jolasa;

import model.Hitza;

/**
 *
 * @author elorza.karmele
 */
public class UrkatuaJFrame extends javax.swing.JFrame {

    /**
     * Creates new form UrkatuaJFrame
     */
    public UrkatuaJFrame() {
        initComponents();
        jButtonBerrizHasi.setVisible(false);
        jLabelAsmatutakoa.setText(hitza.getStrAsmatutakoa());
        System.out.println(hitza.getHitza());
        System.out.println(hitza.getPista());
        System.out.println(hitza.getPuntuazioa());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelIzenburua = new javax.swing.JLabel();
        jLabelSartuHizkia = new javax.swing.JLabel();
        jTextFieldHizkia = new javax.swing.JTextField();
        jButtonEgiaztatu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelHitza = new javax.swing.JLabel();
        jLabelImg = new javax.swing.JLabel();
        jLabelAgertuEzHizkiak = new javax.swing.JLabel();
        jLabelAsmatutakoa = new javax.swing.JLabel();
        jLabelPista = new javax.swing.JLabel();
        jButtonPista = new javax.swing.JButton();
        jButtonBerrizHasi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Urkatua_Karmele");

        jLabelIzenburua.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabelIzenburua.setText("URKATUAREN JOLASA");

        jLabelSartuHizkia.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabelSartuHizkia.setText("Sartu hizkia:");

        jButtonEgiaztatu.setText("Egiaztatu");
        jButtonEgiaztatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEgiaztatuActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabel1.setText("Orain arteko agertu ez diren hizkiak:");

        jLabelAsmatutakoa.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        jButtonPista.setText("Pista");
        jButtonPista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPistaActionPerformed(evt);
            }
        });

        jButtonBerrizHasi.setText("Berriz hasi");
        jButtonBerrizHasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBerrizHasiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabelSartuHizkia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldHizkia, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jButtonEgiaztatu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonPista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonBerrizHasi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabelHitza, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabelAgertuEzHizkiak, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelIzenburua, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAsmatutakoa, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jLabelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabelIzenburua, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSartuHizkia)
                    .addComponent(jTextFieldHizkia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEgiaztatu)
                    .addComponent(jButtonPista)
                    .addComponent(jButtonBerrizHasi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelAgertuEzHizkiak, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabelHitza, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelAsmatutakoa, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPista, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

      private void jButtonEgiaztatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEgiaztatuActionPerformed
          // TODO add your handling code here:
          if (hitza.egiaztatu(jTextFieldHizkia.getText().charAt(0))) { 
              jLabelAsmatutakoa.setText(hitza.getStrAsmatutakoa());
              if (hitza.asmatua()) {
                  System.out.println("Irabazi duzu!.");
                  jLabelImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/irudiak/irabazi.png")));
                  jButtonEgiaztatu.setVisible(false);
                  jButtonPista.setVisible(false);
                  jButtonBerrizHasi.setVisible(true);
                  
              }
          } else {
              erroreak = erroreak + jTextFieldHizkia.getText().charAt(0) + ' ' + ' ';

              jLabelAgertuEzHizkiak.setText(erroreak);
              jLabelImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/irudiak/" + hutsak + ".png")));
              hutsak++;
              if (hutsak == 9) {
                  System.out.println("Galdu duzu!.");
                  jLabelImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/irudiak/galdu.png")));
                  jButtonEgiaztatu.setVisible(false);
                  jButtonPista.setVisible(false);
                  jLabelAsmatutakoa.setText(hitza.getHitza());
                  jButtonBerrizHasi.setVisible(true);
                  hitza.gordePuntuazioa();
              }
          }
          jTextFieldHizkia.setText(null);

      }//GEN-LAST:event_jButtonEgiaztatuActionPerformed

    private void jButtonPistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPistaActionPerformed
        // TODO add your handling code here:
        jLabelPista.setText(hitza.getPista());
    }//GEN-LAST:event_jButtonPistaActionPerformed

    private void jButtonBerrizHasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBerrizHasiActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new UrkatuaJFrame().setVisible(true);
    }//GEN-LAST:event_jButtonBerrizHasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UrkatuaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UrkatuaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UrkatuaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UrkatuaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UrkatuaJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBerrizHasi;
    private javax.swing.JButton jButtonEgiaztatu;
    private javax.swing.JButton jButtonPista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAgertuEzHizkiak;
    private javax.swing.JLabel jLabelAsmatutakoa;
    private javax.swing.JLabel jLabelHitza;
    private javax.swing.JLabel jLabelImg;
    private javax.swing.JLabel jLabelIzenburua;
    private javax.swing.JLabel jLabelPista;
    private javax.swing.JLabel jLabelSartuHizkia;
    private javax.swing.JTextField jTextFieldHizkia;
    // End of variables declaration//GEN-END:variables

    private Hitza hitza = new Hitza();
    private int hutsak = 0;
    private String erroreak = "";
}
